// 多語資料：繁中對照 + 目標語言（英/西/日）
// 結構：decks 為卡片主題；conversations 為日常會話情境

const DATA = {
  decks: {
    common: {
      title: "常用字詞",
      category: "基礎",
      cards: [
        {
          zh: "你好",
          en: "Hello",
          es: "Hola",
          ja: "こんにちは",
          note: "基本問候。",
        },
        {
          zh: "謝謝",
          en: "Thank you",
          es: "Gracias",
          ja: "ありがとうございます",
          note: "表達感謝。",
        },
        {
          zh: "請",
          en: "Please",
          es: "Por favor",
          ja: "お願いします",
          note: "禮貌用語。",
        },
        {
          zh: "對不起",
          en: "Sorry",
          es: "Perdón",
          ja: "ごめんなさい",
          note: "道歉。",
        },
        {
          zh: "再見",
          en: "Goodbye",
          es: "Adiós",
          ja: "さようなら",
          note: "告別用語。",
        },
        {
          zh: "是",
          en: "Yes",
          es: "Sí",
          ja: "はい",
          note: "肯定回答。",
        },
        {
          zh: "不是",
          en: "No",
          es: "No",
          ja: "いいえ",
          note: "否定回答。",
        },
        {
          zh: "好",
          en: "Good",
          es: "Bueno",
          ja: "良い",
          note: "正面評價。",
        },
        {
          zh: "壞",
          en: "Bad",
          es: "Malo",
          ja: "悪い",
          note: "負面評價。",
        },
        {
          zh: "名字",
          en: "Name",
          es: "Nombre",
          ja: "名前",
          note: "個人稱謂。",
        },
      ],
    },
    travel: {
      title: "旅行場景",
      category: "旅行",
      cards: [
        { zh: "車站", en: "station", es: "estación", ja: "駅", note: "交通設施。" },
        { zh: "機場", en: "airport", es: "aeropuerto", ja: "空港", note: "航空交通。" },
        { zh: "護照", en: "passport", es: "pasaporte", ja: "パスポート", note: "旅行證件。" },
        { zh: "機票", en: "ticket", es: "boleto", ja: "チケット", note: "交通票券。" },
        { zh: "行李", en: "luggage", es: "equipaje", ja: "荷物", note: "隨身物品。" },
        { zh: "預約", en: "reservation", es: "reserva", ja: "予約", note: "事先安排。" },
        { zh: "導遊", en: "guide", es: "guía", ja: "ガイド", note: "旅遊引導。" },
        { zh: "地圖", en: "map", es: "mapa", ja: "地図", note: "位置指引。" },
        { zh: "紀念品", en: "souvenir", es: "recuerdo", ja: "お土産", note: "紀念物品。" },
        { zh: "風景", en: "scenery", es: "paisaje", ja: "景色", note: "自然景觀。" },
      ],
    },
    daily: {
      title: "生活常用",
      category: "生活",
      cards: [
        { zh: "餓", en: "hungry", es: "hambriento", ja: "お腹がすいた", note: "飢餓感。" },
        { zh: "累", en: "tired", es: "cansado", ja: "疲れた", note: "疲勞狀態。" },
        { zh: "幫忙", en: "help", es: "ayuda", ja: "助け", note: "協助。" },
        { zh: "好吃", en: "delicious", es: "delicioso", ja: "おいしい", note: "美味。" },
        { zh: "口渴", en: "thirsty", es: "sediento", ja: "のどが渇いた", note: "缺水感。" },
        { zh: "舒服", en: "comfortable", es: "cómodo", ja: "快適", note: "舒適感。" },
        { zh: "乾淨", en: "clean", es: "limpio", ja: "きれい", note: "清潔。" },
        { zh: "安靜", en: "quiet", es: "tranquilo", ja: "静か", note: "安靜。" },
        { zh: "熱鬧", en: "lively", es: "animado", ja: "賑やか", note: "熱鬧。" },
        { zh: "方便", en: "convenient", es: "conveniente", ja: "便利", note: "便利性。" },
      ],
    },
    transport: {
      title: "交通出行",
      category: "交通",
      cards: [
        { zh: "公車", en: "bus", es: "autobús", ja: "バス", note: "公共汽車。" },
        { zh: "計程車", en: "taxi", es: "taxi", ja: "タクシー", note: "計程車。" },
        { zh: "地鐵", en: "metro", es: "metro", ja: "地下鉄", note: "地下鐵路。" },
        { zh: "火車", en: "train", es: "tren", ja: "電車", note: "鐵路列車。" },
        { zh: "腳踏車", en: "bicycle", es: "bicicleta", ja: "自転車", note: "自行車。" },
        { zh: "摩托車", en: "motorcycle", es: "motocicleta", ja: "オートバイ", note: "機車。" },
        { zh: "船", en: "ship", es: "barco", ja: "船", note: "船舶。" },
        { zh: "飛機", en: "airplane", es: "avión", ja: "飛行機", note: "航空器。" },
        { zh: "票", en: "ticket", es: "boleto", ja: "切符", note: "票券。" },
        { zh: "站", en: "stop", es: "parada", ja: "停留所", note: "停靠點。" },
      ],
    },
    lodging: {
      title: "住宿飯店",
      category: "住宿",
      cards: [
        { zh: "飯店", en: "hotel", es: "hotel", ja: "ホテル", note: "住宿設施。" },
        { zh: "房間", en: "room", es: "habitación", ja: "部屋", note: "住宿空間。" },
        { zh: "鑰匙", en: "key", es: "llave", ja: "鍵", note: "開門工具。" },
        { zh: "早餐", en: "breakfast", es: "desayuno", ja: "朝食", note: "早晨餐點。" },
        { zh: "退房", en: "checkout", es: "salida", ja: "チェックアウト", note: "離開住宿。" },
        { zh: "入住", en: "checkin", es: "llegada", ja: "チェックイン", note: "進入住宿。" },
        { zh: "櫃檯", en: "reception", es: "recepcion", ja: "フロント", note: "服務台。" },
        { zh: "電梯", en: "elevator", es: "ascensor", ja: "エレベーター", note: "垂直運輸。" },
        { zh: "樓層", en: "floor", es: "piso", ja: "階", note: "建築層級。" },
        { zh: "服務", en: "service", es: "servicio", ja: "サービス", note: "協助項目。" },
      ],
    },
    business: {
      title: "商務交流",
      category: "商務",
      cards: [
        { zh: "合作", en: "cooperation", es: "cooperación", ja: "協力", note: "共同工作。" },
        { zh: "報價", en: "quotation", es: "cotización", ja: "見積もり", note: "價格估算。" },
        { zh: "會議", en: "meeting", es: "reunión", ja: "会議", note: "集會討論。" },
        { zh: "回覆", en: "reply", es: "respuesta", ja: "返信", note: "回應。" },
        { zh: "合約", en: "contract", es: "contrato", ja: "契約", note: "協議文件。" },
        { zh: "客戶", en: "client", es: "cliente", ja: "顧客", note: "服務對象。" },
        { zh: "專案", en: "project", es: "proyecto", ja: "プロジェクト", note: "工作計畫。" },
        { zh: "預算", en: "budget", es: "presupuesto", ja: "予算", note: "財務規劃。" },
        { zh: "報告", en: "report", es: "informe", ja: "レポート", note: "資訊文件。" },
        { zh: "團隊", en: "team", es: "equipo", ja: "チーム", note: "工作群組。" },
      ],
    },
    medical: {
      title: "醫療看診",
      category: "醫療",
      cards: [
        { zh: "痛", en: "pain", es: "dolor", ja: "痛み", note: "身體不適。" },
        { zh: "發燒", en: "fever", es: "fiebre", ja: "熱", note: "體溫升高。" },
        { zh: "過敏", en: "allergy", es: "alergia", ja: "アレルギー", note: "過敏反應。" },
        { zh: "處方", en: "prescription", es: "receta", ja: "処方箋", note: "醫師指示。" },
        { zh: "藥", en: "medicine", es: "medicina", ja: "薬", note: "治療藥物。" },
        { zh: "醫院", en: "hospital", es: "hospital", ja: "病院", note: "醫療機構。" },
        { zh: "醫師", en: "doctor", es: "médico", ja: "医者", note: "醫療人員。" },
        { zh: "護士", en: "nurse", es: "enfermera", ja: "看護師", note: "護理人員。" },
        { zh: "症狀", en: "symptom", es: "síntoma", ja: "症状", note: "疾病表現。" },
        { zh: "治療", en: "treatment", es: "tratamiento", ja: "治療", note: "醫療處置。" },
      ],
    },
    shopping: {
      title: "購物結帳",
      category: "購物",
      cards: [
        { zh: "試穿", en: "try on", es: "probarse", ja: "試着", note: "試穿衣物。" },
        { zh: "尺寸", en: "size", es: "talla", ja: "サイズ", note: "衣物大小。" },
        { zh: "信用卡", en: "credit card", es: "tarjeta de crédito", ja: "クレジットカード", note: "付款方式。" },
        { zh: "折扣", en: "discount", es: "descuento", ja: "割引", note: "價格優惠。" },
        { zh: "商店", en: "store", es: "tienda", ja: "店", note: "購物場所。" },
        { zh: "價格", en: "price", es: "precio", ja: "価格", note: "商品費用。" },
        { zh: "收銀台", en: "cashier", es: "caja", ja: "レジ", note: "結帳處。" },
        { zh: "發票", en: "receipt", es: "recibo", ja: "レシート", note: "購物憑證。" },
        { zh: "購物袋", en: "shopping bag", es: "bolsa", ja: "買い物袋", note: "裝載物品。" },
        { zh: "特價", en: "sale", es: "oferta", ja: "セール", note: "促銷活動。" },
      ],
    },
    school: {
      title: "校園學習",
      category: "校園",
      cards: [
        { zh: "課程", en: "class", es: "clase", ja: "授業", note: "學習單元。" },
        { zh: "圖書館", en: "library", es: "biblioteca", ja: "図書館", note: "書籍場所。" },
        { zh: "作業", en: "homework", es: "tarea", ja: "宿題", note: "課後練習。" },
        { zh: "獎學金", en: "scholarship", es: "beca", ja: "奨学金", note: "學習補助。" },
        { zh: "學生", en: "student", es: "estudiante", ja: "学生", note: "學習者。" },
        { zh: "老師", en: "teacher", es: "profesor", ja: "先生", note: "教學者。" },
        { zh: "考試", en: "exam", es: "examen", ja: "試験", note: "學習評量。" },
        { zh: "筆記", en: "notes", es: "apuntes", ja: "ノート", note: "學習記錄。" },
        { zh: "書本", en: "book", es: "libro", ja: "本", note: "學習材料。" },
        { zh: "成績", en: "grade", es: "nota", ja: "成績", note: "學習成果。" },
      ],
    },
    phone: {
      title: "電話與網路",
      category: "電話與網路",
      cards: [
        { zh: "網路", en: "internet", es: "internet", ja: "インターネット", note: "網路連線。" },
        { zh: "訊號", en: "signal", es: "señal", ja: "電波", note: "通訊品質。" },
        { zh: "密碼", en: "password", es: "contraseña", ja: "パスワード", note: "安全驗證。" },
        { zh: "熱點", en: "hotspot", es: "punto de acceso", ja: "ホットスポット", note: "網路分享。" },
        { zh: "電話", en: "phone", es: "teléfono", ja: "電話", note: "通訊設備。" },
        { zh: "簡訊", en: "message", es: "mensaje", ja: "メッセージ", note: "文字通訊。" },
        { zh: "通話", en: "call", es: "llamada", ja: "通話", note: "語音通訊。" },
        { zh: "接聽", en: "answer", es: "contestar", ja: "出る", note: "回應來電。" },
        { zh: "掛斷", en: "hang up", es: "colgar", ja: "切る", note: "結束通話。" },
        { zh: "留言", en: "voicemail", es: "buzón de voz", ja: "留守番電話", note: "語音留言。" },
      ],
    },
    weather: {
      title: "天氣與季節",
      category: "天氣",
      cards: [
        { zh: "天氣", en: "weather", es: "clima", ja: "天気", note: "氣候狀況。" },
        { zh: "雨", en: "rain", es: "lluvia", ja: "雨", note: "降水。" },
        { zh: "冷", en: "cold", es: "frío", ja: "寒い", note: "低溫。" },
        { zh: "熱", en: "hot", es: "calor", ja: "暑い", note: "高溫。" },
        { zh: "太陽", en: "sun", es: "sol", ja: "太陽", note: "恆星。" },
        { zh: "雲", en: "cloud", es: "nube", ja: "雲", note: "大氣現象。" },
        { zh: "風", en: "wind", es: "viento", ja: "風", note: "空氣流動。" },
        { zh: "雪", en: "snow", es: "nieve", ja: "雪", note: "固態降水。" },
        { zh: "春天", en: "spring", es: "primavera", ja: "春", note: "季節。" },
        { zh: "秋天", en: "autumn", es: "otoño", ja: "秋", note: "季節。" },
      ],
    },
    time: {
      title: "數字與時間",
      category: "時間",
      cards: [
        { zh: "時間", en: "time", es: "tiempo", ja: "時間", note: "時序概念。" },
        { zh: "小時", en: "hour", es: "hora", ja: "時間", note: "時間單位。" },
        { zh: "分鐘", en: "minute", es: "minuto", ja: "分", note: "時間單位。" },
        { zh: "遲到", en: "late", es: "tarde", ja: "遅い", note: "時間延遲。" },
        { zh: "明天", en: "tomorrow", es: "mañana", ja: "明日", note: "未來時間。" },
        { zh: "昨天", en: "yesterday", es: "ayer", ja: "昨日", note: "過去時間。" },
        { zh: "今天", en: "today", es: "hoy", ja: "今日", note: "現在時間。" },
        { zh: "星期", en: "week", es: "semana", ja: "週", note: "時間週期。" },
        { zh: "月份", en: "month", es: "mes", ja: "月", note: "時間週期。" },
        { zh: "年份", en: "year", es: "año", ja: "年", note: "時間週期。" },
      ],
    },
  },
  conversations: [
    {
      id: "cafe",
      title: "咖啡店點餐",
      category: "餐飲",
      lines: [
        {
          role: "店員",
          zh: "歡迎光臨，請問要點什麼？",
          en: "Welcome! What would you like to order?",
          es: "¡Bienvenido! ¿Qué desea pedir?",
          ja: "いらっしゃいませ。ご注文は何になさいますか？",
        },
        {
          role: "我",
          zh: "一杯拿鐵，少糖，內用。",
          en: "A latte, less sugar, for here, please.",
          es: "Un café con leche, menos azúcar, para aquí, por favor.",
          ja: "ラテを砂糖少なめで、店内でお願いします。",
        },
        {
          role: "店員",
          zh: "好的，還需要其他的嗎？",
          en: "Sure. Anything else?",
          es: "Claro. ¿Algo más?",
          ja: "かしこまりました。他にご注文は？",
        },
        {
          role: "我",
          zh: "不用了，謝謝。",
          en: "That's all, thank you.",
          es: "Nada más, gracias.",
          ja: "以上で、ありがとうございます。",
        },
      ],
    },
    {
      id: "greet",
      title: "初次見面",
      category: "社交",
      lines: [
        { role: "A", zh: "你好！我叫小林。", en: "Hi! I'm Lin.", es: "¡Hola! Soy Lin.", ja: "こんにちは！リンです。" },
        { role: "B", zh: "很高興認識你。", en: "Nice to meet you.", es: "Encantado de conocerte.", ja: "はじめまして。" },
        { role: "A", zh: "你從哪裡來？", en: "Where are you from?", es: "¿De dónde eres?", ja: "どちらのご出身ですか？" },
        { role: "B", zh: "我來自台灣。", en: "I'm from Taiwan.", es: "Soy de Taiwán.", ja: "台湾から来ました。" },
      ],
    },
    {
      id: "hotel-checkin",
      title: "飯店辦理入住",
      category: "住宿",
      lines: [
        { role: "櫃檯", zh: "請問有預約嗎？", en: "Do you have a reservation?", es: "¿Tiene una reserva?", ja: "ご予約はございますか？" },
        { role: "我", zh: "有的，林先生，兩晚。", en: "Yes, under Lin, two nights.", es: "Sí, a nombre de Lin, dos noches.", ja: "はい、リンで2泊です。" },
        { role: "櫃檯", zh: "這是您的房卡，電梯在那邊。", en: "Here are your keys, the elevator is over there.", es: "Aquí están sus llaves, el ascensor está por allá.", ja: "こちらが鍵です。エレベーターはあちらです。" },
      ],
    },
    {
      id: "ask-directions",
      title: "問路與導航",
      category: "交通",
      lines: [
        { role: "我", zh: "請問到博物館怎麼走？", en: "How do I get to the museum?", es: "¿Cómo llego al museo?", ja: "博物館へはどう行きますか？" },
        { role: "路人", zh: "直走兩個路口右轉。", en: "Go straight for two blocks and turn right.", es: "Siga derecho dos cuadras y gire a la derecha.", ja: "二つ先の角までまっすぐ行って右に曲がってください。" },
      ],
    },
    {
      id: "biz-meeting",
      title: "商務開會",
      category: "商務",
      lines: [
        { role: "A", zh: "我們先看議程。", en: "Let's go over the agenda first.", es: "Revisemos la agenda primero.", ja: "まず議題を確認しましょう。" },
        { role: "B", zh: "有任何更新嗎？", en: "Any updates?", es: "¿Alguna novedad?", ja: "更新はありますか？" },
      ],
    },
    {
      id: "clinic",
      title: "看診與症狀描述",
      category: "醫療",
      lines: [
        { role: "醫師", zh: "哪裡不舒服？", en: "Where does it hurt?", es: "¿Dónde le duele?", ja: "どこが痛いですか？" },
        { role: "我", zh: "喉嚨痛，還有點發燒。", en: "Sore throat and a little fever.", es: "Me duele la garganta y tengo un poco de fiebre.", ja: "喉が痛くて、少し熱があります。" },
      ],
    },
    {
      id: "mall-shopping",
      title: "逛街購物",
      category: "購物",
      lines: [
        { role: "我", zh: "這件有小一號嗎？", en: "Do you have this in a smaller size?", es: "¿Lo tiene en una talla más pequeña?", ja: "これの小さいサイズはありますか？" },
        { role: "店員", zh: "我幫您找看看。", en: "Let me check for you.", es: "Déjeme revisar.", ja: "お調べします。" },
      ],
    },
    {
      id: "airport",
      title: "機場報到",
      category: "旅行",
      lines: [
        { role: "地勤", zh: "請出示護照與機票。", en: "Passport and ticket, please.", es: "Pasaporte y boleto, por favor.", ja: "パスポートとチケットをお願いします。" },
        { role: "我", zh: "這是我的行李。", en: "This is my luggage.", es: "Este es mi equipaje.", ja: "こちらが荷物です。" },
      ],
    },
    {
      id: "phone-call",
      title: "打電話與留言",
      category: "電話與網路",
      lines: [
        { role: "我", zh: "喂，請找林先生。", en: "Hello, may I speak to Mr. Lin?", es: "Hola, ¿puedo hablar con el señor Lin?", ja: "もしもし、リンさんをお願いします。" },
        { role: "對方", zh: "他不在，我幫你留言。", en: "He's not here. I can take a message.", es: "No está. Puedo tomar un recado.", ja: "今はいません。伝言を承ります。" },
      ],
    },
    {
      id: "classroom",
      title: "課堂互動",
      category: "校園",
      lines: [
        { role: "老師", zh: "有問題嗎？", en: "Any questions?", es: "¿Alguna pregunta?", ja: "質問はありますか？" },
        { role: "學生", zh: "可以再解釋一次嗎？", en: "Could you explain again?", es: "¿Podría explicar de nuevo?", ja: "もう一度説明していただけますか？" },
      ],
    },
    {
      id: "bus",
      title: "公車地鐵",
      category: "交通",
      lines: [
        { role: "我", zh: "到市中心要轉車嗎？", en: "Do I need to transfer to get downtown?", es: "¿Debo hacer transbordo para llegar al centro?", ja: "中心街へ行くには乗り換えが必要ですか？" },
        { role: "站務", zh: "在下一站轉乘二號線。", en: "Transfer to Line 2 at the next station.", es: "Transborde a la línea 2 en la próxima estación.", ja: "次の駅で2号線に乗り換えてください。" },
      ],
    },
    {
      id: "weather-talk",
      title: "天氣寒暄",
      category: "天氣",
      lines: [
        { role: "A", zh: "今天好熱喔。", en: "It's so hot today.", es: "Hace mucho calor hoy.", ja: "今日はとても暑いですね。" },
        { role: "B", zh: "是啊，記得補充水分。", en: "Yeah, stay hydrated.", es: "Sí, mantente hidratado.", ja: "そうですね。水分補給を忘れずに。" },
      ],
    },
    {
      id: "restaurant-reserve",
      title: "餐廳訂位",
      category: "餐飲",
      lines: [
        { role: "我", zh: "我要訂今晚七點，兩位。", en: "I'd like to book for 7 pm, two people.", es: "Quisiera reservar a las 7 pm, para dos personas.", ja: "今夜7時に2名で予約したいです。" },
        { role: "店員", zh: "好的，請留下電話。", en: "Sure, please leave a phone number.", es: "Claro, por favor deje un número de teléfono.", ja: "かしこまりました。お電話番号をお願いします。" },
      ],
    },
  ],
};

// 將資料掛到全域
window.APP_DATA = DATA;


